apiVersion: v1
kind: Namespace
metadata:
  name: profile-picture-frame
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-picture-frame
  namespace: profile-picture-frame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-picture-frame
  template:
    metadata:
      labels:
        app: profile-picture-frame
    spec:
      containers:
        - name: profile-picture-frame
          image: container-registry-test.zalando.net/flo/profile-picture-frame:latest
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              cpu: 10m
              memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: profile-picture-frame
  namespace: profile-picture-frame
spec:
  selector:
    app: profile-picture-frame
  ports:
    - port: 80
      targetPort: 9090
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: profile-picture-frame
  namespace: profile-picture-frame
spec:
  rules:
    - host: profile-picture-frame.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: profile-picture-frame
                port:
                  number: 80
